### PR TITLE
Relax warnings as errors so we can build on Clang 11

### PR DESCRIPTION
**Pull request by nrc**
This prevents TiKV building on MacOS.

PTAL @yiwu-arbug @Little-Wallace

### CODE REVIEW

**Comment by Connor1996** [comment]
Busy working on other things, sorry for not fixing it in time. Thanks!

**Comment by yiwu-arbug** [comment]
@nrc Adding these flags to corresponding rust-rocksdb build.rs scripts would avoid the need to modify rocksdb. Do you mind sending a PR there instead?

**Comment by nrc** [comment]
@yiwu-arbug I don't know how to do that - I tried adding `cfg.cxxflag("-Wno-error=shadow");` to `build_rocksdb`, but I still got the new errors when building.

**Comment by aknuds1** [comment]
Thanks, presuming this fixes TiKV build on OS X.

**Comment by yiwu-arbug** [comment]
@nrc have you try adding `cxxflag("-Wno-error=shadow")` to both librocksdb/build.rs and librocksdb/libtitan/build.rs?

**Comment by yiwu-arbug** [comment]
@nrc I'm not able to test since I cannot reproduce the error on my mac (also with clang 11). Don't know why :(

**Comment by nrc** [comment]
> have you try adding cxxflag("-Wno-error=shadow") to both librocksdb/build.rs and librocksdb/libtitan/build.rs?

I have, and it still fails - from the logs, the flags are being passed to cmake properly, but I think the flags from CMakeLists.txt override them? I'm not sure about either Clang's or CMake's behaviour tbh.

Thinking about it I think it might be better to fix it here (and in Titan) rather than rust-rocksdb, since this will be a problem for people building these projects outside of rust-rocksdb too.

**Comment by nrc** [comment]
Seems like the unknown error is causing problems with older Clang on CI

**Comment by Hoverbear** [comment]
Seems related to https://github.com/pingcap/rust-rocksdb/issues/295

**Comment by yiwu-arbug** [comment]
> > have you try adding cxxflag("-Wno-error=shadow") to both librocksdb/build.rs and librocksdb/libtitan/build.rs?
> 
> I have, and it still fails - from the logs, the flags are being passed to cmake properly, but I think the flags from CMakeLists.txt override them? I'm not sure about either Clang's or CMake's behaviour tbh.
> 
> Thinking about it I think it might be better to fix it here (and in Titan) rather than rust-rocksdb, since this will be a problem for people building these projects outside of rust-rocksdb too.

just tried and seems it's because rocksdb's CMakeList.txt sets -Wshadow, which comes later in the compile command and override what's set from build.rs. I'm okay to land this. Do you mind fix the build? Seems CI is not happy with `-Wno-error=defaulted-function-deleted`.

**Pull request merged**
